sudo: false
language: ruby
rvm:
  - 2.3.4
env:
  - TARGET=redmine REDMINE_VERSION=3.3.4
  - TARGET=plugin REDMINE_VERSION=3.3.4
  - TARGET=redmine REDMINE_VERSION=3.4.2
  - TARGET=plugin REDMINE_VERSION=3.4.2
before_install: sh travis/before_install.sh
script: sh travis/exec_test.sh
addons:
  apt:
    packages:
    - cvs
